#' @title  run_packages
#' @description import use_packaged pkgs
#' @example
#' run_packages()
#'
#' @export
################################################################################

run_packages <- function()
{
  print(' pkgs to import:...')
  rm(list = ls())
  ################################################################################
  # packages
  # add for loops to install any if not exist
  library(devtools)
  library('devtools')
  library('BiocParallel')
  # library('tispec')
  # library(lsa)
  library('dplyr')
  library('olsrr')
  library('gridExtra')
  library('matrixStats')
  library('STRINGdb')
  library('corpcor')
  library('mixOmics')
  #library('tidyverse',type = "depends")
  library("reticulate")
  library('ggplot2')
  library('ggpubr')
  library('RColorBrewer')
  library('psych')
  library('reshape')
  library('Seurat')
  library('ggrepel')
  library('fastICA')
  library('pheatmap')
  #library('slanter')
  library('corrplot')
  #library(EnhancedVolcano)
  library('rbioapi')
  library('PRROC')
  #library("genefilter")
  #devtools::install_bioc('ReactomePA')
  library('ReactomePA')
  library('uwot')
  library('plyr');
  # library('tidyr')
  library("org.Mm.eg.db")
  library("org.Hs.eg.db")
  # library('KEGG.db')
  library('reactome.db')
  library('clusterProfiler')
  # library('pROC')
  library('sjmisc')
  # library('R.oo')
  library('stringr')
  #library('nichenetr')
  library('irlba')
  #library('PCAtools')
  library('ComplexHeatmap')

  options(ggrepel.max.overlaps = Inf)
  use_package('devtools')
  use_package('BiocParallel')
  # use_package('tispec')
  # use_package(lsa)
  use_package('dplyr')
  use_package('olsrr')
  use_package('gridExtra')
  use_package('matrixStats')
  use_package('STRINGdb')
  use_package('corpcor')
  use_package('mixOmics')
  #use_package('tidyverse',type = "depends")
  use_package("reticulate")
  use_package('ggplot2')
  use_package('ggpubr')
  use_package('RColorBrewer')
  use_package('psych')
  use_package('reshape')
  use_package('Seurat')
  use_package('ggrepel')
  use_package('fastICA')
  use_package('pheatmap')
  #use_package('slanter')
  use_package('corrplot')
  #use_package(EnhancedVolcano)
  use_package('rbioapi')
  use_package('PRROC')
  #use_package("genefilter")
  #devtools::install_bioc('ReactomePA')
  use_package('ReactomePA')

  use_package('uwot')
  use_package('plyr');
  # use_package('tidyr')
  use_package("org.Mm.eg.db")
  use_package("org.Hs.eg.db")
  # use_package('KEGG.db')
  use_package('reactome.db')
  use_package('clusterProfiler')
  # use_package('pROC')
  use_package('sjmisc')
  # use_package('R.oo')
  use_package('stringr')
  #use_package('nichenetr')
  use_package('irlba')
  #use_package('PCAtools')
  use_package('ComplexHeatmap')
  args = commandArgs(trailingOnly=TRUE)
}


